name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use Node.js 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build the package
      run: npm run build # Run build script if needed

    - name: Publish to npm packages
      run: |
          echo "Publishing node packages"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
